name: Build and Commit Gemma Model

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Download converter script
        run: |
          mkdir -p tools
          curl -L https://raw.githubusercontent.com/xenova/transformers.js/main/scripts/convert.js -o tools/convert.js

      - name: Convert Gemma 3n-E2B-it to ONNX
        run: |
          export HUGGING_FACE_HUB_TOKEN=${{ secrets.HF_TOKEN }}
          node tools/convert.js \
            --model google/gemma-3n-E2B-it \
            --quantize int8 \
            --output ./models/gemma-3n-E2B-it/

      - name: Commit and push model files if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/gemma-3n-E2B-it
          if ! git diff --cached --quiet; then
            git commit -m "Update Gemma 3n-E2B-it ONNX model"
            git push
          else
            echo "No changes to commit."
          fi
